#!/bin/sh
#-
# Copyright (c) 2016 Bartek Rutkowski
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# $FreeBSD$

: ${DIALOG_OK=0}

echo -n > $BSDINSTALL_TMPETC/rc.conf.hardening
echo -n > $BSDINSTALL_TMPETC/sysctl.conf.hardening

exec 3>&1
FEATURES=$( dialog --backtitle "Installazione Firew4ll" \
    --title "System Hardening" --nocancel --notags --separate-output \
    --checklist "Scegli le opzioni di rafforzamento della sicurezza del sistema:" \
    0 0 0 \
	"hide_uids" "Nascondi i processi in esecuzione come altri utenti" ${hide_uids:-off} \
	"hide_gids" "Nascondi i processi in esecuzione come altri gruppi" ${hide_gids:-off} \
	"read_msgbuf" "Disabilita la lettura del buffer dei messaggi del kernel per utenti normali" ${read_msgbuf:-off} \
	"proc_debug" "Disabilitare le funzionalità di debug dei processi per utenti normali" ${proc_debug:-off} \
	"random_pid" "Randomizza il PID dei processi appena creati" ${random_pid:-off} \
	"stack_guard" "Insert stack guard page ahead of the growable segments" ${stack_guard:-off} \
	"clear_tmp" "Pulisci /tmp all'avvio del sistema" ${clear_tmp:-off} \
	"disable_syslogd" "Disabilita l'apertura del socket di rete Syslogd (disabilita la registrazione remota)" ${disable_syslogd:-off} \
	"disable_sendmail" "Disabilita il servizio Sendmail" ${disable_sendmail:-off} \
2>&1 1>&3 )
exec 3>&-

for feature in $FEATURES; do
	if [ "$feature" = "hide_uids" ]; then
		echo security.bsd.see_other_uids=0 >> $BSDINSTALL_TMPETC/sysctl.conf.hardening
	fi
	if [ "$feature" = "hide_gids" ]; then
		echo security.bsd.see_other_gids=0 >> $BSDINSTALL_TMPETC/sysctl.conf.hardening
	fi
	if [ "$feature" = "read_msgbuf" ]; then
		echo security.bsd.unprivileged_read_msgbuf=0 >> $BSDINSTALL_TMPETC/sysctl.conf.hardening
	fi
	if [ "$feature" = "proc_debug" ]; then
		echo security.bsd.unprivileged_proc_debug=0 >> $BSDINSTALL_TMPETC/sysctl.conf.hardening
	fi
	if [ "$feature" = "random_pid" ]; then
		echo kern.randompid=1 >> $BSDINSTALL_TMPETC/sysctl.conf.hardening
	fi
	if [ "$feature" = "stack_guard" ]; then
		echo security.bsd.stack_guard_page=1 >> $BSDINSTALL_TMPETC/sysctl.conf.hardening
	fi
	if [ "$feature" = "clear_tmp" ]; then
		echo 'clear_tmp_enable="YES"' >> $BSDINSTALL_TMPETC/rc.conf.hardening
	fi
	if [ "$feature" = "disable_syslogd" ]; then
		echo 'syslogd_flags="-ss"' >> $BSDINSTALL_TMPETC/rc.conf.hardening
	fi
	if [ "$feature" = "disable_sendmail" ]; then
		echo 'sendmail_enable="NONE"' >> $BSDINSTALL_TMPETC/rc.conf.hardening
	fi
done
