#!/bin/sh
#-
# Copyright (c) 2011 Nathan Whitehorn
# Copyright (c) 2013-2015 Devin Teske
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# $FreeBSD$
#
############################################################ INCLUDES

BSDCFG_SHARE="/usr/share/bsdconfig"
. $BSDCFG_SHARE/common.subr || exit 1

############################################################ MAIN

f_dprintf "Installazione iniziata il %s" "$( date )"
export BSDINSTALL_CHROOT=$1

error() {
	local msg
	if [ -n "$1" ]; then
		msg="$1\n\n"
	fi
	dialog --backtitle "Installazione Firew4ll" --title "Annulla" \
	    --no-label "Esci" --yes-label "Riavvia" --yesno \
	    "${msg}Una fase dell'installazione è stata interrotta. Riavviare l'installazione o uscire dal programma di installazione?" 0 0
	if [ $? -ne 0 ]; then
		exit
	else
		exec $0 $BSDINSTALL_CHROOT
	fi
}


rm -rf $BSDINSTALL_TMPETC
mkdir $BSDINSTALL_TMPETC
mkdir -p $1 || error "mkdir fallito per $1"

test ! -d $BSDINSTALL_DISTDIR && mkdir -p $BSDINSTALL_DISTDIR

if [ ! -f $BSDINSTALL_DISTDIR/MANIFEST -a -z "$BSDINSTALL_DISTSITE" ]; then
	exec 3>&1
	BSDINSTALL_DISTSITE=$(`dirname $0`/mirrorselect 2>&1 1>&3)
	MIRROR_BUTTON=$?
	exec 3>&-
	test $MIRROR_BUTTON -eq 0 || error "Nessun mirror selezionato"
	export BSDINSTALL_DISTSITE
	fetch -o $BSDINSTALL_DISTDIR/MANIFEST $BSDINSTALL_DISTSITE/MANIFEST || error "Non puoi scaricare $BSDINSTALL_DISTSITE/MANIFEST"
fi

export DISTRIBUTIONS="base.txz"
if [ -f $BSDINSTALL_DISTDIR/MANIFEST ]; then
	DISTMENU=`cut -f 4,5,6 $BSDINSTALL_DISTDIR/MANIFEST | grep -v -e ^kernel -e ^base`

	exec 3>&1
	EXTRA_DISTS=$(echo $DISTMENU | xargs dialog \
	    --backtitle "Installazione Firew4ll" \
	    --title "Seleziona Distribuzuibe" --nocancel --separate-output \
	    --checklist "Scegli i componenti opzionali da installare:" \
	    0 0 0 \
	2>&1 1>&3)
	for dist in $EXTRA_DISTS; do
		export DISTRIBUTIONS="$DISTRIBUTIONS $dist.txz"
	done
fi

FETCH_DISTRIBUTIONS=""
for dist in $DISTRIBUTIONS; do
	if [ ! -f $BSDINSTALL_DISTDIR/$dist ]; then
		FETCH_DISTRIBUTIONS="$FETCH_DISTRIBUTIONS $dist"
	fi
done
FETCH_DISTRIBUTIONS=`echo $FETCH_DISTRIBUTIONS`	# Trim white space

if [ -n "$FETCH_DISTRIBUTIONS" -a -z "$BSDINSTALL_DISTSITE" ]; then
	exec 3>&1
	BSDINSTALL_DISTSITE=`bsdinstall mirrorselect 2>&1 1>&3`
	MIRROR_BUTTON=$?
	exec 3>&-
	test $MIRROR_BUTTON -eq 0 || error "Nessun mirror selezionato"
	export BSDINSTALL_DISTSITE
fi

if [ ! -z "$FETCH_DISTRIBUTIONS" ]; then
	bsdinstall distfetch || error "Failed to fetch distribution"
fi

bsdinstall checksum || error "Distribution checksum fallita"
bsdinstall distextract || error "Distribution extract fallita"
bsdinstall rootpass || error "Password  di root non settata"

trap true SIGINT	# This section is optional
bsdinstall services

dialog --backtitle "Installazione Firew4ll" --title "Aggiungi Account Utente" --yesno \
    "Desideri aggiungere utenti al sistema installato ora?" 0 0 && \
    bsdinstall adduser

trap error SIGINT	# SIGINT is bad again
bsdinstall config  || error "Salvataggio configurazione fallita"
cp /etc/resolv.conf $1/etc
cp /etc/localtime $1/etc

bsdinstall entropy

f_dprintf "Installazione completata il %s" "$(date)"
exit $SUCCESS

################################################################################
# END
################################################################################
